In [1]:
# Dependencies
import requests
from bs4 import BeautifulSoup
import pandas as pd

## Extract Data from the cdc.gov website

In [2]:
# URL of page to be scraped
url = 'https://www.cdc.gov/sleep/data_statistics.html'

In [3]:
# Retrieve page with the requests module
response = requests.get(url)

In [4]:
response

In [5]:
# Create BeautifulSoup object; parse with 'html.parser'
soup = BeautifulSoup(response.text, 'html.parser')

In [7]:
results = soup.find_all('tr')
len(results)

62

In [8]:
#this gets you the info out of the tables
results[0].text

'\nCharacteristic\n%\n95% Confidence Interval\n'

In [9]:
# Loop through the html, return results and store in a list
sleep_data = []
for result in results:
    row_data = result.text.strip()
    sleep_data.append(row_data)
    print(row_data)

Characteristic
%
95% Confidence Interval
All Adultsa
35.2
(34.9–35.5)
Sexa
Men
35.5
(35.1–36.0)
Women
34.8
(34.4–35.2)
Age (Years)
18–24
32.2
(31.3–33.2)
25–34
37.9
(37.1–38.7)
35–44
38.3
(37.5–39.1)
45–54
39.0
(38.3–39.6)
55–64
35.6
(34.9–36.2)
≥65
26.3
(25.8–26.8)
Race/Ethnicitya
White
33.4
(33.0–33.7)
Hispanic
34.5
(33.6–35.5)
Black
45.8
(44.9–46.8)
Asian
37.5
(35.2–39.7)
American Indian/Alaska Native
40.4
(37.9–43.0)
Native Hawaiian/Pacific Islander
46.3
(39.9–52.8)
Other/Multiracial
44.3
(42.4–46.2)
Short sleep
(<7 hours)


Sufficient sleep
(≥7 hours)
Health risk factor
Definition
%
95% CI
%
95% CI
Obese
Body Mass Index ≥30 kg/m2
33.0
(32.5–33.5)
26.5
(26.2–26.9)
Physically inactive
No leisure time physical activity in past 30 days
27.2
(26.8–27.7)
20.9
(20.6–21.2)
Current smoker
Currently smoke cigarettes every day or some days
22.9
(22.4–23.4)
14.9
(14.6–15.2)
Excessive alcohol
Underage drinker, binge drinker, or heavy drinkerb
19.4
(18.9–19.8)
19.1
(18.7–19.4)
Short sleep
(<7 hours)


Sufficient sleep
(≥7 hours)
Chronic condition
%
95% CI
%
95% CI
Heart attack
4.8
(4.6–5.0)
3.4
(3.3–3.5)
Coronary heart disease
4.7
(4.5–4.9)
3.4
(3.3–3.5)
Stroke
3.6
(3.4–3.8)
2.4
(2.3–2.5)
Asthma
16.5
(16.1–16.9)
11.8
(11.5–12.0)
COPD (chronic obstructive pulmonary disease)
8.6
(8.3–8.9)
4.7
(4.6–4.8)
Cancer
10.2
(10.0–10.5)
9.8
(9.7–10.0)
Arthritis
28.8
(28.4–29.2)
20.5
(20.2–20.7)
Depression
22.9
(22.5–23.3)
14.6
(14.3–14.8)
Chronic kidney disease
3.3
(3.1–3.5)
2.2
(2.1–2.3)
Diabetes
11.1
(10.8–11.4)
8.6
(8.4–8.8)
Short sleep duration (<8 hours)
Characteristic
%a
95% Confidence Interval
Total
68.8
(68.0–69.6)
Survey year
2007
69.0
(67.0–70.9)
2009
69.1
(67.5–70.6)
2011
68.6
(67.2–69.9)
2013
68.4
(66.9–69.9)
Sex
Female
71.3
(70.4–72.1)
Male
66.4
(65.4–67.4)
Grade
9th
59.7
(58.6–60.8)
10th
67.4
(66.1–68.8)
11th
73.3
(72.0–74.5)
12th
76.6
(75.4–77.8)
Race/ethnicity
Whiteb
68.3
(67.3–69.4)
Blackb
71.2
(69.9–72.5)
Hispanic
67.0
(65.5–68.5)
American Indian/Alaska Nativeb
60.3
(52.4–67.6)
Asianb
75.7
(72.7–78.5)
Native Hawaiian/Pacific Islanderb
68.3
(62.1–73.9)
Multiracialb
72.0
(69.2–74.7)

In [11]:
# Creating a dataframe object from list
sleep_df = pd.DataFrame(sleep_data) 
sleep_df.head()

                                            0
0  Characteristic\n%\n95% Confidence Interval
1              All Adultsa\n35.2\n(34.9–35.5)
2                                        Sexa
3                      Men\n35.5\n(35.1–36.0)
4                    Women\n34.8\n(34.4–35.2)

In [12]:
# Separate the values separated by "/n" into columns
sleep_data_df = sleep_df[0].str.split("\n", n = 5, expand = True)
#sleep_data_df

In [22]:
# Rows 0-19 of sleep_data_df have the values in Table 1 which we are not interested in 
# For reference: Table 1 Short Sleep Duration (<7 Hours) by Sex, Age, and Race/Ethnicity 
# — Behavioral Risk Factor Surveillance System, United States, 2014

table_1 = sleep_data_df.iloc[:19,:]
table_1.head(10)

                0     1                        2     3     4     5
0  Characteristic     %  95% Confidence Interval  None  None  None
1     All Adultsa  35.2              (34.9–35.5)  None  None  None
2            Sexa  None                     None  None  None  None
3             Men  35.5              (35.1–36.0)  None  None  None
4           Women  34.8              (34.4–35.2)  None  None  None
5     Age (Years)  None                     None  None  None  None
6           18–24  32.2              (31.3–33.2)  None  None  None
7           25–34  37.9              (37.1–38.7)  None  None  None
8           35–44  38.3              (37.5–39.1)  None  None  None
9           45–54  39.0              (38.3–39.6)  None  None  None

## Transfer the Health Risk Factor DataFrame

In [26]:
# Rows 20-25 of sleep_data_df have the values in Table 2 which we are interested in 
# For reference: Table 2. Age-Adjusteda Percentage Reporting Health Risk Factors by Sleep Duration
# —Behavioral Risk Factor Surveillance System, United States, 2014

table_2_old = sleep_data_df.iloc[20:25,:]
#clean data by renaming the needed columns
table_2_old.rename(columns={0:'Health Risk Factor', 1:'Health Risk Definition', 2:'Short Sleep (<7 hours)', 4:'Sufficient Sleep (≥7 Hours)'}, inplace=True)
#clean data by removing the columns that are not needed
t2 = table_2_old.drop([3,5], axis=1)
#clean data by dropping the rows that are not needed
table_2 = t2.drop([20,21])
#clean data by resetting the index
table_2.set_index("Health Risk Factor", inplace=True)
table_2

,Health Risk Definition,Short Sleep (<7 hours),Sufficient Sleep (≥7 Hours)
Health Risk Factor,,,
Obese,Body Mass Index ≥30 kg/m2,33.0,26.5
Physically inactive,No leisure time physical activity in past 30 days,27.2,20.9
Current smoker,Currently smoke cigarettes every day or some days,22.9,14.9

## Transform the Chronic Condition DataFrame

In [27]:
# Rows 26-37 of sleep_data_df have the values in Table 3 which we are interested in 
# For reference: Table 3. Age-Adjusteda Percentage Reporting Chronic Health Conditions by Sleep Duration
# —Behavioral Risk Factor Surveillance System, United States, 2014

table_3_old = sleep_data_df.iloc[26:37,:]
#clean data by renaming the needed columns
table_3_old.rename(columns={0:'Chronic Condition', 1:'<7 Hours Sleep', 3: '≥7 Hours Sleep'}, inplace=True)
#clean data by dropping the columns that are not needed
t3 = table_3_old.drop([2,4,5], axis=1)
#clean data by dropping the rows that are not needed
table_3 = t3.drop([26,27])
#clean data by resetting the index
table_3.set_index("Chronic Condition", inplace=True)
table_3

                                             <7 Hours Sleep ≥7 Hours Sleep
Chronic Condition
Heart attack                                            4.8            3.4
Coronary heart disease                                  4.7            3.4
Stroke                                                  3.6            2.4
Asthma                                                 16.5           11.8
COPD (chronic obstructive pulmonary disease)            8.6            4.7
Cancer                                                 10.2            9.8
Arthritis                                              28.8           20.5
Depression                                             22.9           14.6
Chronic kidney disease                                  3.3            2.2

In [28]:
# Rows 38-61 of sleep_data_df have the values in Table 4 which we are Not interested in 
# For reference: Table 4. Short Sleep Duration by Selected Characteristics
# — Youth Risk Behavior Survey, United States, 2007–2013.
table_4 = sleep_data_df.iloc[38:,:]
table_4.head()

,0,1,2,3,4,5
38,Short sleep duration (<8 hours),None,None,None,None,None
39,Characteristic,%a,95% Confidence Interval,None,None,None
40,Total,68.8,(68.0–69.6),None,None,None
41,Survey year,None,None,None,None,None
42,2007,69.0,(67.0–70.9),None,None,None

### Create database connection

In [ ]:
# connection_string = "postgres:postgres@localhost:5432/sleep_db"
# engine = create_engine(f'postgresql://{connection_string}')

In [ ]:
# Confirm tables
# engine.table_names()

### Load DataFrames into database

In [ ]:
#table_2.to_sql(name='health_risk', con=engine, if_exists='append', index=True)

In [ ]:
#table_3.to_sql(name='chronic_condition', con=engine, if_exists='append', index=True)